id: Level 1
controller: 
    time: 10000
graphic:
    name: GraphicPygame
    args:
        data_image_dir: data_image

map:
    name: GameMap
    args:
        path: data_maps/map_5.txt
player:
    -   name: Seeker
        count: 1
        args:
            movable: True
            view_range: 3
    -   name: Hider
        count: 1
        args:
            movable: False 
            view_range: 2

    
    # ... more metrics